#name: Close inactive issues
#
#on:
#  schedule:
#    - cron: "30 1 * * *"
#
#jobs:
#  close-issues:
#    runs-on: ubuntu-latest
#    permissions:
#      issues: write
#      pull-requests: write
#    steps:
#      - name: Check for stale issues and pull requests
#        uses: "pascalgn/automerge-action@v0.15.0"
#        with:
#          stale-issue-message: "This issue is stale because it has been open for 10 days with no activity."
#          close-issue-message: "This issue was closed because it has been inactive for 10 days since being marked as stale."
#          stale-pr-message: "This pull request is stale because it has not been updated for 10 days."
#          close-pr-message: "This pull request was closed because it has been inactive for 10 days since being marked as stale."
#          days-before-stale: 10
#          days-before-close: 10
#          days-before-pr-stale: -1
#          days-before-pr-close: -1
#          stale-label: "stale"
#          exempt-label: "in progress"
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"